#!/bin/bash

# dependencies: jq, curl

usage () {
    printf "dict by yazoink (2023)\nusage: dict [word1] [word2] [etc]\n"
}

defineall() {
    for ((i=1; i<=$#; i++)); do
        jsondata="$(curl -s https://api.dictionaryapi.dev/api/v2/entries/en/"${!i}")"
        if [[ "$jsondata" == *"phonetic"* ]]; then
            definitions=($(getdefinitions "$jsondata"))
            phonetic=$(getphonetic "$jsondata")
            printf "\033[1m%s\033[0m \033[0;31m%s\033[0m\n" "${!i}" "$phonetic"
            counter=1
            for ((j=0; j<${#definitions[@]}; j++)); do
                printf "\033[1;36m%s)\033[0m %s\n" "$counter" "$(echo "${definitions[j]}" | sed 's/-/ /g')"
                ((counter++))
            done
            if [[ "$i" != "$#" ]]; then
                printf "\n"
            fi
        else
            printf "\033[1m%s\033[0m could not be found in the dictionary.\n" "${!i}"
        fi
    done
}

getphonetic () {
    phonetic=$(echo "$jsondata" | jq -r '.[0].phonetics.[1].text')
    if [[ "$phonetic" == "null" ]]; then
        echo ""
    else
        echo "("$phonetic")"
    fi
}

getdefinitions () {
    i=0
    while read -r line; do
        definitions[i]=$(echo "$line" | sed 's/ /-/g')
        ((i++))
    done < <(echo "$1" | jq -r '.[0].meanings[].definitions[].definition')
    echo "${definitions[@]}"
}

case "$1" in
    -h | --help | "") usage && exit 0 ;;
    *) defineall "$@" && exit 0 ;;
esac
